name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!! from Actions"
      - name: Print good bye
        run: echo "Good Bye"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Second Job TEst"
      - name: Print good bye
        run: echo "Good Bye Second job"
